language: android
jdk:
  - oraclejdk8

sudo: false

env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_BUILD_TOOLS_VERSION=23.0.2
    - ADB_INSTALL_TIMEOUT=10
    - COVERALLS_REPO_TOKEN=t2TbIvhp87JhVGaK0tFkihmMwfN5aVlQQ
    - CODECOV_TOKEN= 462eb948-9d37-4302-b2c4-1d4195f30631

  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

script: "./gradlew build"
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools

    - tools
      - platform-tools
      - build-tools-23.0.2
      - android-23

      - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

  script:
    - ./gradlew build jacocoTestReport assembleAndroidTest
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
    - ./gradlew connectedCheck

  before_install:
  - pip install --user codecov

  after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov

  deploy:
    provider: script
    script: "./gradlew bintrayUpload"
    on:
      tags: true



  cache:
    directories:
    - "$HOME/.gradle/caches/"



