language: android
jdk:
  - oraclejdk8

env:
  global:
    - COVERALLS_REPO_TOKEN=t2TbIvhp87JhVGaK0tFkihmMwfN5aVlQQ
    - CODECOV_TOKEN=462eb948-9d37-4302-b2c4-1d4195f30631

script: "./gradlew build"
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - oldPlatform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

  cache:
    directories:
    - "$HOME/.gradle/caches/"
  script:
  - "./gradlew build jacocoTestReport"

  after_success:
  - bash <(curl -s https://codecov.io/bash)

  deploy:
    provider: script
    script: "./gradlew bintrayUpload"
    on:
      tags: true

before_install:
  - pip install --user codecov

after_success:
  - codecov


